server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /documentation {
        rewrite ^/documentation/?$ /index.html break;
        rewrite ^/documentation/(.*)$ /$1 break;
        try_files $uri $uri/ $uri.html /index.html;
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
