import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  librariesSidebar: [
    'libraries',
    {
      type: 'category',
      label: 'RAPTOR',
      link: {
        type: 'doc',
        id: 'libraries/raptor/index',
      },
      items: [
        {
          type: 'category',
          label: 'raptor-gtfs-pipeline',
          link: {
            type: 'doc',
            id: 'libraries/raptor/raptor-gtfs-pipeline/index',
          },
          items: [
            'libraries/raptor/raptor-gtfs-pipeline/getting-started',
            'libraries/raptor/raptor-gtfs-pipeline/cli-reference',
            'libraries/raptor/raptor-gtfs-pipeline/binary-format',
            'libraries/raptor/raptor-gtfs-pipeline/service-periods',
            'libraries/raptor/raptor-gtfs-pipeline/validation',
          ],
        },
        {
          type: 'category',
          label: 'raptor-kt',
          items: [
            {
              type: 'autogenerated',
              dirName: 'libraries/raptor/raptor-kt',
            },
          ],
        },
        {
          type: 'category',
          label: 'raptor-sw',
          items: [
            {
              type: 'autogenerated',
              dirName: 'libraries/raptor/raptor-sw',
            },
          ],
        },
      ],
    }
  ],
  apisSidebar: [
    'apis',
  ],
};

export default sidebars;