import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  librariesSidebar: [
    'overview',
    {
      type: 'category',
      label: 'raptor-gtfs-pipeline',
      link: {
        type: 'doc',
        id: 'libraries/raptor/raptor-gtfs-pipeline/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'libraries/raptor/raptor-gtfs-pipeline',
        },
      ],
    },
    {
      type: 'category',
      label: 'raptor-kt',
      link: {
        type: 'doc',
        id: 'libraries/raptor/raptor-kt/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'libraries/raptor/raptor-kt',
        },
      ],
    },
  ]
};

export default sidebars;